name: CI Foundry Tests

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Foundry
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
